version: '3.8'

services:
  app:
    image: docker.voelkerlabs.de/dinner-notification-backend
    container_name: dinner_notification_backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
      - DATABASE_USER=your_db_user
      - DATABASE_PASSWORD=your_db_password
      - BASIC_AUTH_USER=user
      - BASIC_AUTH_PASSWORD=test123
    depends_on:
      - db
    networks:
      - internal_network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal_network

volumes:
  db_data:

networks:
  internal_network:
    driver: bridge