package com.voelkerlabs.dinner_notification.exception

import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.ExceptionHandler
import org.springframework.web.bind.annotation.RestControllerAdvice

@RestControllerAdvice
class GlobalExceptionHandling {

    @ExceptionHandler(UserNotFoundException::class)
    fun handleUserNotFoundException(exception: UserNotFoundException): ResponseEntity<String> {
        return ResponseEntity.status(404).body(exception.message)
    }

    @ExceptionHandler(UnexpectedNullAutogeneratedException::class)
    fun handleUserNotFoundException(exception: UnexpectedNullAutogeneratedException): ResponseEntity<String> {
        return ResponseEntity.status(500).body(exception.message)
    }
}