package com.voelkerlabs.dinner_notification.exception

import java.lang.RuntimeException

class UnexpectedNullAutogeneratedException : RuntimeException {
    constructor() : super("Unexpected null for autogenerated value")
}