name: build-docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/dinner-notification-backend .

      - name: Push Docker Image to Registry
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/dinner-notification-backend
